subscription newMessageSended($data: NewMessageSendedDto!){
    newMessageSended(data: $data){
        id
        sender{
            id
            email
            password
            firstName
            lastName
            conversations{
                id
                createdAt
                participants{
                    id
                    email
                    password
                    firstName
                    lastName
                    conversations{
                        id
                        createdAt
                    }
                    status
                    name
                }
                messages{
                    id
                    sender{
                        id
                        email
                        password
                        firstName
                        lastName
                        status
                        name
                    }
                    message
                    unread
                    createdAt
                }
            }
            status
            name
        }
        message
        unread
        createdAt
    }
}